FROM ubuntu:xenial
RUN apt-get update && apt-get install -y mysql-client
RUN apt-get update && apt-get install -y cmake libmysqlclient-dev g++ git libboost-dev make zlib1g-dev
RUN git clone https://github.com/OlafvdSpek/xbt
WORKDIR /xbt/Tracker
RUN cmake .
RUN make
ADD docker-run-xbt.sh /root/run-xbt.sh
ADD xbt_tracker.conf xbt_tracker.conf
ENTRYPOINT ["/bin/bash", "/root/run-xbt.sh"]
EXPOSE 2710
