version: "2"
linters:
  exclusions:
    presets:
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - goconst
        path: _test\.go
      - linters:
          - gosec
        text: 'G401:'
      - linters:
          - gosec
        text: 'G505:'
      - linters:
          - gosec
        path: internal/mse/
